host: 127.0.0.1
port: 3000
ssl: false

db:
# PLEASE NOTE: you should not use synchronize after development as you will mostlikely lose data if the server every unfortantely crashes.
  name: connection1
  type: mariadb
  host: 127.0.0.1
  port: 3306
  username: root
  password: ''
  database: test
  synchronize: true
  entities: [src/**/entity/*.js]
  # Multiple connection example
  # -
  #   name: connection1
  #   type: mariadb
  #   host: 127.0.0.1
  #   port: 3306
  #   username: root
  #   password: ''
  #   database: test
  #   synchronize: true
  #   entities: [src/**/entity/*.js]
  # -
  #     name: connection2
  #     type: mariadb
  #     host: 127.0.0.1
  #     port: 3306
  #     username: root
  #     password: ''
  #     database: test2
  #     synchronize: true
  #     entities: [src/**/entity/*.js]

